### ISSUE TITLE
ESP expects the top level module name to match the configuration name and end with '_dma<32|64>'

### ISSUE THREAD

**Issue by paulmnt** [IBM/esp-chisel-accelerators#33]
The FFT accelerator generates one configuration only: '_Default_dma32', however, the corresponding RTL module is assigned the name 'FFTAccelerator_Default_fft32' instead of  'FFTAccelerator_Default_dma32'

**Comment by seldridge** [comment]
Cool. I should have this fixed in #36. I just want to clarify first: what string can be used to replace `Default`? Something in `[a-zA-Z0-9]`? Basically, any word that doens't contain `_`?

**Comment by paulmnt** [comment]
Actually, any string will do, even if it includes `_`. The only things that matter are:
- the prefix `<AcceleratorName>_` (e.g. FFTAccelerator_)
- the suffix `_dma[32|64]` (e.g. _dma32)
